steps:
  - label: "🪟🛠 Windows Bundle "
    key: "windows_bundle"
    commands:
      - "flutter clean"
      - "flutter pub get"
      - "flutter pub run build_runner build --delete-conflicting-outputs"
      - "flutter test"
      - "flutter build windows"
      - "flutter pub run msix:create"
    agents:
      os: "windows"