steps:
  - label: "🧽 Clean 🧽, 🛠 build 🛠, 🔬 test 🔬 "
    key: "clean_test"
    command:
    - "make clean_test"
    - "rsync -ar ./ /tmp/buildkite/$$BUILDKITE_COMMIT/"
    agents:
      os: "macOS"

  - label: "📱 iOS Build 🏭 "
    key: "ios_build"
    depends_on:
      - "clean_test"
    command:
    - "rsync -ar /tmp/buildkite/$$BUILDKITE_COMMIT/ ./"
    - "make ios_build_ipa"
    - "rsync -ar ./ /tmp/buildkite/$$BUILDKITE_COMMIT/"
    artifact_paths:
      - "missing_translations.txt"
    agents:
      os: "macOS"

  - label: "📱 iOS fastlane build 👟 "
    key: "ios_fastlane_build"
    depends_on:
      - "ios_build"
    command:
    - "rsync -ar /tmp/buildkite/$$BUILDKITE_COMMIT/ ./"
    - "make ios_fastlane_build"
    - "rsync -ar ./ /tmp/buildkite/$$BUILDKITE_COMMIT/"
    agents:
      os: "macOS"

  - label: "📱 iOS fastlane TestFlight upload 🚀 "
    key: "ios_fastlane_testflight"
    depends_on:
      - "ios_fastlane_build"
    command:
    - "rsync -ar /tmp/buildkite/$$BUILDKITE_COMMIT/ ./"
    - "make ios_fastlane_upload"
    agents:
      os: "macOS"

  - label: "💻 macOS Build 🏭 "
    key: "macos_build"
    depends_on:
      - "clean_test"
    command:
      - "rsync -ar /tmp/buildkite/$$BUILDKITE_COMMIT/ ./"
      - "make macos_build_flutter"
      - "rsync -ar ./ /tmp/buildkite/$$BUILDKITE_COMMIT/"
    artifact_paths:
      - "missing_translations.txt"
    agents:
      os: "macOS"

  - label: "💻 macOS fastlane build 👟 "
    key: "macos_fastlane_build"
    depends_on:
      - "macos_build"
    command:
      - "rsync -ar /tmp/buildkite/$$BUILDKITE_COMMIT/ ./"
      - "make macos_fastlane_build"
      - "rsync -ar ./ /tmp/buildkite/$$BUILDKITE_COMMIT/"
    agents:
      os: "macOS"

  - label: "💻 macOS fastlane TestFlight upload 🚀 "
    key: "macos_fastlane_testflight"
    depends_on:
      - "macos_fastlane_build"
    command:
      - "rsync -ar /tmp/buildkite/$$BUILDKITE_COMMIT/ ./"
      - "make macos_fastlane_upload"
    agents:
      os: "macOS"

  - label: "💻 macOS fastlane Export 🚀 "
    key: "macos_fastlane_export"
    depends_on:
      - "macos_build"
    command:
      - "rsync -ar /tmp/buildkite/$$BUILDKITE_COMMIT/ ./"
      - "make macos_fastlane_export"
      - "rsync -ar ./ /tmp/buildkite/$$BUILDKITE_COMMIT/"
    artifact_paths:
      - "build/export/Lotti.app"
    agents:
      os: "macOS"

  - label: "💻 macOS create DMG file 💾 "
    key: "macos_dmg"
    depends_on:
      - "macos_fastlane_export"
    command:
      - "rsync -ar /tmp/buildkite/$$BUILDKITE_COMMIT/ ./"
      - "npx create-dmg build/export/Lotti.app build/export/"
      - "rsync -ar ./ /tmp/buildkite/$$BUILDKITE_COMMIT/"
    agents:
      os: "macOS"

  - label: "💻 macOS notarize DMG file ⚖️ "
    key: "macos_notarize"
    depends_on:
      - "macos_dmg"
    command:
      - "rsync -ar /tmp/buildkite/$$BUILDKITE_COMMIT/ ./"
      - "xcrun altool --notarize-app -f build/export/*.dmg --primary-bundle-id com.matthiasnehlsen.lotti -u $$APPLEID -p $$APPLEIDPASS"
    agents:
      os: "macOS"

  - label: "💻 macOS publish GitHub prerelease 🚀 "
    key: "macos_github_prerelease"
    depends_on:
      - "macos_notarize"
    command:
      - "rsync -ar /tmp/buildkite/$$BUILDKITE_COMMIT/ ./"
      - "gh release create -p -d --generate-notes --target $$BUILDKITE_COMMIT $$BUILDKITE_BRANCH build/export/*.dmg"
    agents:
      os: "macOS"

######################

  - label: "🐧 Clean 🧽, 🛠 build 🛠, 🔬 test 🔬 "
    key: "linux_clean_test"
    command:
      - "make clean_test"
      - "mkdir -p /tmp/buildkite/$$BUILDKITE_COMMIT/"
      - "rsync -ar ./ /tmp/buildkite/$$BUILDKITE_COMMIT/"
    agents:
      os: "linux"

  - label: "🐧 Linux Build 🏭 "
    key: "linux_build"
    depends_on:
      - "linux_clean_test"
    command:
      - "rsync -ar /tmp/buildkite/$$BUILDKITE_COMMIT/ ./"
      - "make linux_build"
      - "tar cfvz build/linux.x64.tar.gz build/linux"
      - "rsync -ar ./ /tmp/buildkite/$$BUILDKITE_COMMIT/"
    artifact_paths:
      - "missing_translations.txt"
    agents:
      os: "linux"

  - label: "🐧 Linux publish GitHub prerelease 🚀 "
    key: "linux_github_prerelease"
    depends_on:
      - "linux_build"
    command:
      - "rsync -ar /tmp/buildkite/$$BUILDKITE_COMMIT/ ./"
      - "gh release create -p -d --generate-notes --target $$BUILDKITE_COMMIT $$BUILDKITE_BRANCH build/linux.x64.tar.gz"
    agents:
      os: "linux"
